### ISSUE TITLE
Different cropping method

### ISSUE THREAD

**Issue by KruskalLin** [JuanLuisGonzalez/FAL_net#2]
Hi, Juan! Thanks for your great work, I appreciate it! As you already show the evaluation code, I found out that you are using different cropping methods 
https://github.com/JuanLuisGonzalez/FAL_net/blob/ee35df6e77ccddd4835b7aac9e9fbd57b7d30a6d/myUtils.py#L265

May I ask why don't you use Garg crop or Eigen crop for evaluation?

**Comment by JuanLuisGonzalez** [comment]
Hello Lin,

It is supposed to be equivalent to Garg crop.

Juan Luis

**Comment by KruskalLin** [comment]
No, it isn't. I know you are to unify the predicted depth map and ground truth map.  While I use your crop the  2nd pretrained model's result turned out to be
![crop](https://user-images.githubusercontent.com/30172175/120115639-2fcbe680-c1b7-11eb-9686-efc1eea9e852.png)
But when I use the code from Monodepth/Monodepth2 where the crop is
```python
crop = np.array([0.40810811 * gt_height, 0.99189189 * gt_height,  
0.03594771 * gt_width,  0.96405229 * gt_width]).astype(np.int32)
```
the depth result from your 2nd pretrained model decreases as
![garg_crop](https://user-images.githubusercontent.com/30172175/120115643-365a5e00-c1b7-11eb-9bc8-868306fa5e24.png)

So did I misunderstand something? Or can I deem this as another cropping method?

**Comment by JuanLuisGonzalez** [comment]
Thanks for pointing that out,

In our crop, we used the exact pixel coordinates to make the crop as we
evaluate at the original resolutions, in the Monodepth2 they multiplied the
image dimensions by the relative coordinates. Still, both codes are based
on Garg crop. The metrics don't seem to change much.

Juan Luis

**Comment by KruskalLin** [comment]
Yeah, so the above result I post is without multiplying the width in the evaluation. Besides, the evaluation code you use is applying the width_to_focal dict. As far as I know, this is only used for testing KITTI stereo dataset since the original Eigen split may have different focal lengths and baseline under the same width. While I used this code
```python
focal_length, baseline = get_focal_length_baseline(gt_calib[t_id], camera_id)
depth_pred = (baseline * focal_length) / disp_pred
```
instead of
```python
width_to_focal[im_sizes[t_id][1]] * width_to_baseline[im_sizes[t_id][1]] / (disp_pred + (1 - disp_mask))
```
the result is getting worse
<img width="639" alt="dict" src="https://user-images.githubusercontent.com/30172175/120173771-f33fcf80-c236-11eb-9b41-b628c604574c.png">
