### ISSUE TITLE
about the exponential disparity

### ISSUE THREAD

**Issue by guogangok** [JuanLuisGonzalez/FAL_net#4]
FAL_netA.py, line 225, exponential disparity is formulated as : w = max_disp * torch.exp(torch.log(max_disp / min_disp) * (c - 1)), which is equal to: w = max_disp*pow(max_disp/min_disp, c-1) ,  it is a power function, would you please explain this?
Thank you.

**Comment by JuanLuisGonzalez** [comment]
Hello, your observation is correct. It can be simplified.
